ecal_test :
  extends: .rec_benchmark
  when: manual
  stage: benchmarks1
  script:
    - python3 ECal/run_benchmark.py -c ../solid.xml -t ecal_test -n 10000 --particle "e-" --p-min 3 --p-max 3 --angle-min 15 --angle-max 15
